#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Logopeda.Resource", IsApplication=true)]

namespace Logopeda
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int TypesArray = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001a
			public const int ALL = 2131099674;
			
			// aapt resource value: 0x7f06000f
			public const int Add = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int CZ = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int DZ = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int DŻ = 2131099671;
			
			// aapt resource value: 0x7f060011
			public const int MainLayout = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int Poems = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int PoemsList = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int RZ = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int S = 2131099673;
			
			// aapt resource value: 0x7f060013
			public const int SZ = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int SZCZ = 2131099670;
			
			// aapt resource value: 0x7f06000e
			public const int Sentences = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int WordRowItem = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int Words = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int cancelButton = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int content_Text = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int content_Title = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int groupSpinner = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int groupSpinner_Title = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int poem_Title = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int poem_TitleEdit = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int saveButton = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int subgroupSpinner = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int subgroupSpinner_Title = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int typeSpinner = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int typeSpinner_Title = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PoemsListScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PoemsScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int WordsListScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int WordsScreen = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int Add = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int All = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040015
			public const int Cancel = 2130968597;
			
			// aapt resource value: 0x7f04000d
			public const int Group = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int Poem = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int PoemContent = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int PoemTitle = 2130968594;
			
			// aapt resource value: 0x7f040003
			public const int Poems = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int PoemsList = 2130968587;
			
			// aapt resource value: 0x7f040014
			public const int Save = 2130968596;
			
			// aapt resource value: 0x7f040006
			public const int Sentence = 2130968582;
			
			// aapt resource value: 0x7f040010
			public const int SentenceContent = 2130968592;
			
			// aapt resource value: 0x7f040005
			public const int Sentences = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int SentencesList = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int Subgroup = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int Type = 2130968595;
			
			// aapt resource value: 0x7f040002
			public const int Word = 2130968578;
			
			// aapt resource value: 0x7f04000f
			public const int WordContent = 2130968591;
			
			// aapt resource value: 0x7f040001
			public const int Words = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int WordsList = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int WordsTypes = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
